# Fashion MNIST

## Importing libraries

In [1]:
import sys
sys.path.append('../') 
from imports import *
import torch, torchvision
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms

## Loading dataset

In [2]:
# Define a transform to normalize the data
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

train_dataset = torchvision.datasets.FashionMNIST(root="./data", download=False, train=True, transform=transform)
test_dataset = torchvision.datasets.FashionMNIST(root="./data", download=False, train=False, transform=transform)

In [3]:
# Get targets from the dataset
targets = train_dataset.targets.numpy()

# Stratified split of indices
train_idx, val_idx = train_test_split(
    np.arange(len(targets)),
    test_size=0.1,
    shuffle=True,
    stratify=targets
)

# Extracting training, validation and test data and targets
train_data = train_dataset.data[train_idx].numpy()
val_data = train_dataset.data[val_idx].numpy()
test_data = test_dataset.data.numpy()

train_targets = train_dataset.targets[train_idx].numpy()
val_targets = train_dataset.targets[val_idx].numpy()
test_targets = test_dataset.targets.numpy()

# Save the datasets to disk
np.save('./fashion-mnist-processed-data/train_data.npy', train_data)
np.save('./fashion-mnist-processed-data/val_data.npy', val_data)
np.save('./fashion-mnist-processed-data/test_data.npy', test_data)

np.save('./fashion-mnist-processed-data/train_targets.npy', train_targets)
np.save('./fashion-mnist-processed-data/val_targets.npy', val_targets)
np.save('./fashion-mnist-processed-data/test_targets.npy', test_targets)

print("Datasets saved successfully.")

Datasets saved successfully.


## EDA

In [4]:
np.bincount(train_targets), np.bincount(val_targets), np.bincount(test_targets)

# same count of each class in train, val and test sets, so no class imbalance

(array([5400, 5400, 5400, 5400, 5400, 5400, 5400, 5400, 5400, 5400]),
 array([600, 600, 600, 600, 600, 600, 600, 600, 600, 600]),
 array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]))